name: Nightly Release
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  check_date:
    name: Check dates
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.code-change.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if code has changed with 24 hours
        continue-on-error: true
        id: code-change
        run: |
          if [[ $(git rev-list --after="24 hours" --first-parent HEAD) ]]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          fi
  build_release:
    name: Build and release Docker image
    runs-on: ubuntu-latest
    needs: check_date
    if: needs.check-date.outputs.should-run == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            type=schedule,pattern=nightly
            type=sha
          labels: ${{ steps.meta.outputs.labels }}
